### ISSUE TITLE
catch messages

### ISSUE THREAD

**Issue by VictorYammouni** [s-u/rJava#218]
hello

I wonder if it is possible to capture the java messages.

I use DBI and RJDBC to connect to different DataBases. The problem with some JDBC drivers, such as HIVE for example, the messages are so incomprehensible that it is impossible for an average user to know what it is

Thnaks and take care of yourself and your loved ones

**Comment by s-u** [comment]
You can, use `tryCatch()` to catch the error messages. However, they are just regular messages that are constructed from the Java exceptions as follows:

```r
stop(..., "\n  JDBC ERROR: ", .jcall(x, "S", "getMessage"), statement)
```

So one improvement we could do is to construct `errorCondition` that includes the exception object so you can get more information if you want.

I'm not sure if that's what you have in mind...

**Comment by VictorYammouni** [comment]
hello

i still get a message, despite the trycatch :

  result<-tryCatch({
    jc <- .jcall("java/sql/DriverManager","Ljava/sql/Connection;","getConnection", as.character(url)[1], as.character(user)[1], as.character(password)[1], check=FALSE)


**avr. 21, 2020 9:34:44 AM org.apache.hive.jdbc.Utils parseURL
INFOS: Supplied authorities: lxpr338a.unix.intra.bdf.local:8443
avr. 21, 2020 9:34:44 AM org.apache.hive.jdbc.Utils parseURL
INFOS: Resolved authority: lxpr338a.unix.intra.bdf.local:8443
avr. 21, 2020 9:34:44 AM org.apache.hive.jdbc.HiveConnection openSession
GRAVE: Error opening session
org.apache.thrift.transport.TTransportException: HTTP Response code: 401
	at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:262)
	at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:313)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.send_OpenSession(TCLIService.java:154)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.OpenSession(TCLIService.java:146)
	at org.apache.hive.jdbc.HiveConnection.openSession(HiveConnection.java:552)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:170)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)**

and i don't how to use in  this case : 

as a reminder, i'm using the RJDBC package to connect to Hive and i modified dbConnect function

Thanks

**Comment by s-u** [comment]
Victor, there are two independent things - Java may be printing output but that is not capturable by R. Then there are exceptions in the driver - those you can catch and operate on. I have updated the error handing in RJDBC 0.2-9 so you can do something like:

```r
> library(RJDBC)
Loading required package: DBI
Loading required package: rJava
> MySQL<-JDBC('org.mariadb.jdbc.Driver','mysql-connector-java.jar',"`")
> tryCatch(dbConnect(MySQL, "jdbc:mysql://localhost/test", user="test", password="test1234"), error=function(e) { cat("Caught error:\n"); str(e); e$jex$printStackTrace() })
Caught error:
List of 5
 $ message  : chr "Unable to connect JDBC to jdbc:mysql://localhost/test\n  JDBC ERROR: Could not connect to address=(host=localho"| __truncated__
 $ call     : language dbConnect(MySQL, "jdbc:mysql://localhost/test", user = "test", password = "test1234")
 $ desc     : chr "Unable to connect JDBC to jdbc:mysql://localhost/test"
 $ jex      :Formal class 'jobjRef' [package "rJava"] with 2 slots
  .. ..@ jobj  :<externalptr> 
  .. ..@ jclass: chr "java/lang/Throwable"
 $ statement: NULL
 - attr(*, "class")= chr [1:10] "JDBC.result.error" "JDBC.exception" "java.sql.SQLNonTransientConnectionException" "java.sql.SQLNonTransientException" ...
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1243)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:622)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
	at org.mariadb.jdbc.Driver.connect(Driver.java:86)
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1238)
	... 3 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
	... 5 more

```

**Comment by VictorYammouni** [comment]
I will try it as soon as possible

Thank's a lot
