### ISSUE TITLE
Problems with "mailR" that uses "rJava"

### ISSUE THREAD

**Issue by andirey** [s-u/rJava#266]
I use "mailR" package for email sending. This package use "rJava". After updates, I start getting the following bugs. Please, help me to fix it. Thanks!

java --version
==
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

Logs
==

java.lang.NoClassDefFoundError: javax/activation/DataHandler
	at org.apache.commons.mail.Email.createMimeMessage(Email.java:1832)
	at org.apache.commons.mail.Email.buildMimeMessage(Email.java:1268)
	at org.apache.commons.mail.Email.send(Email.java:1436)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at RJavaTools.invokeMethod(RJavaTools.java:386)
Caused by: java.lang.ClassNotFoundException
	at RJavaClassLoader.findClass(RJavaClassLoader.java:397)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 8 more
NULL
NoClassDefFoundError (Java): javax/activation/DataHandler[1] "Java-Object{org.apache.commons.mail.SimpleEmail@722c41f4}"

**Comment by s-u** [comment]
Please contact `mailR` support. Other than a bug in `mailR` my guess would be that you may have too old Java version.
