### ISSUE TITLE
Calling rjava from Intellij getting RJavaClassLoader not found

### ISSUE THREAD

**Issue by achuu126** [s-u/rJava#292]
Hi,

I am getting java.lang.NoClassDefFoundError: RJavaClassLoader
	at org.rosuda.JRI.Rengine.rniEval(Native Method)
	at org.rosuda.JRI.Rengine.eval(Rengine.java:549)
 when I tried to call a R script file contains RJDBC to connect to sql server or any of the rJava library methods from my java program.  Without calling rJava methods, the R script run fine using the following method.

@GetMapping("/runScript")
    public void runRScript(@RequestHeader("rFilePath") String rFilePath,
                           @RequestHeader("rFileName") String rFileName) throws RserveException, IOException {

        getREngine();
        REXP l = engine.eval("system.file(\"java\",package=\"rJava\") ")
        engine.eval("source(\"" + "src/main/resources/scripts/" +rFileName + "\")");
        REXP rexp = engine.eval("dtTrendPoints");
        System.out.println("this is dtTrendPoints: " + rexp.toString());
        engine.end();
    }  

My VM option is set to use the JRI 
-Djava.library.path="C:\Users\ntid\Documents\R\win-library\4.0\rJava\jri\x64"

I set up my CLASSPATH in my pc variables
C:\Users\ntid\Documents\R\win-library\4.0\rJava\java;C:\Users\ntid\Documents\R\win-library\4.0\rJava\java\boot;C:\Program Files\Microsoft\R Open\R-4.0.2\library\rJava\java\boot;

My R file:
library(RJDBC)
.jinit(".")
.jengine(TRUE)
system.file("java",package="rJava")
drv <- RJDBC::JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver","C:/Program Files (x86)/Microsoft JDBC Driver 4.0 for SQL Server/sqljdbc_4.0/enu/sqljdbc4.jar")

I am using Microsoft R open and it is installed on my C: and rJava is installed in my user folder.  When I run java, I checked the system file for rJava and it is said in C:\Program Files\Microsoft\R Open\R-4.0.2\library\rJava\java instead of the under my ntid user name folder, so I copied the rJava folder into that R-4.0.2 folder.  I still get the same error.  However, when I run the same system.file command in R it said it is from my user folder.

I am using an older version of JDK 8.0.282.8 and it is 64 bit.

I saw some similar posts awhile back, and tried all the possible solutions listed and still no go.  Any idea how I should set rJava in my local machine?

Thank you very much in advance!

**Comment by s-u** [comment]
@achuu126 I'm somewhat confused how you are starting JRI somehow - what Java program do you run it from? The code above suggests that Rserve is involved, but then you are using JRI and from inside JRI you are calling rJava.

Also it is unclear at which point do you get the error. The `.jinit()` itself is creating a reference to the class loader (BTW: did you really intend to use `"."` as the class path there?), so what is the output of `.jclassLoader()` after .`jinit()`? Also check `.jclassPath()` as well.

Since the above is too incomplete, do you have the full sources somewhere to reproduce? In theory .`jinit()` does all the necessary class path manipulation if possible just after attaching to the JVM. Since it does create a reference to the class loader, it would issue an error if that did not succeed. You can also try setting `-DrJava.debug=1` in your parent Java process to enable class loader debugging in rJava.

**Comment by achuu126** [comment]
Hi @s-u , 

Thank you very much for your reply!  I have a method to start the engine.  I pasted below.  I am trying to write a Java api where it will take in a R script and run it.  There are times we need to connect to the sql server from R script to get the data and thus using RJDBC to connect.  As soon as the code (engine.eval("source(\"" + "src/main/resources/scripts/" +rFileName + "\")");)  hit .jinit().  I get the class not found error and in the console it logs this: Error in .jinit() : Unable to create a Java class loader.  

I do noticed something strange.  When I run and print REXP l = engine.eval("system.file(\"java\",package=\"rJava\") "); in my java program, it gives me this path C:/Program Files/Microsoft/R Open/R-4.0.2/library/rJava/java.  But if I run the same system.file command in R Open, it gives me this C:/Users/ntid/Documents/R/win-library/4.0/rJava/java

Thank you again for your help!

I updated the R script to the following:
library("stringr")
library(RJDBC)
library("rJava")
.jinit( )
drv <- RJDBC::JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver","C:/Program Files (x86)/Microsoft JDBC Driver 4.0 for SQL Server/sqljdbc_4.0/enu/sqljdbc4.jar")

I also tried to put classpath in .jinit() method.  I get the classpath from .jclassPath() while running in R Open.  Gives me the same error with or without .

This is the code I start the rengine:

private void getREngine()
    {
 
        engine = Rengine.getMainEngine();
        if(engine == null){
            engine=new Rengine (new String [] {"--no-save"}, false, new RConsoleLogging.LoggingConsole(log));
            if (!engine.waitForR())
            {
                System.out.println ("Cannot load R");
            }
        }
        if (!engine.waitForR()) {
            System.out.println("Cannot load R");
        }
        System.out.print("JRI R-Engine call: ");
    }

I

**Comment by s-u** [comment]
I'm not sure if this is your problem, but JDK 17 does not allow rJava to be used via JNI (see "Important note to Java developers" in the NEWS about avoiding JDK 17). The way to reproduce:

```
cd $R_HOME/library/rJava/jri
sh run rtest
[...]
> rJava::.jinit()
rBusy(1)
Exception in thread "Thread-0" java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @755c9148
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.rosuda.JRI.Rengine.rniRunMainLoop(Native Method)
	at org.rosuda.JRI.Rengine.run(Rengine.java:640)
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: RJavaClassLoader
	at org.rosuda.JRI.Rengine.rniRunMainLoop(Native Method)
	at org.rosuda.JRI.Rengine.run(Rengine.java:640)
Caused by: java.lang.ClassNotFoundException: RJavaClassLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 2 more
Error in rJava::.jinit() : Unable to create a Java class loader.
In addition: Warning message:
In rJava::.jinit() :
  Another VM is running already and the VM did not allow me to append paths to the class path.
```

This means that any code that wants to embed R in Java and the use `rJava` from there has to create the rJava class loader first and give it to rJava, otherwise rJava cannot control the class loader since the new JNI JDK 17 security rules don't allow it. Try using any JDK before 17 and it should be ok.

Note that core rJava functionality will still work, but anything involving the class loader or `RJavaTools` won't (unless you add those to your own class loader).
