### ISSUE TITLE
Where is the error message

### ISSUE THREAD

**Issue by yudalang3** [s-u/rJava#335]
This is my java code:

```Java
	public String launch() throws Exception {
//		Launcher.main(null);
//		Launcher4Dev.main(null);

		System.err.println("Error:" + new File("").getAbsolutePath());
		System.out.println("Output:" + new File("").getAbsolutePath());

		new InputMismatchException("fejfoejfwef").printStackTrace();

		return "Hello this is eGPS for R!";
	}
```

But I run it in the R:

```R
  setLib_and_launchJVM();
  tryCatch(
    expr = {
      instance <- .jnew(launchClass)
      words <- .jcall(obj = instance, returnSig = "S", method = "launch")
      cat('The words of eGPS Java is: ', words, '\n');

    }
    ,
    Exception = function(e) {
      e$printStackTrace()
    }
  )
```

I can not see any error messages????

**Comment by s-u** [comment]
By default (i.e. unless `setOut` or `setErr` is used) `System.out` goes to `stdout` and `System.err` goes to `stderr`. Stack traces also go to `stderr`. What exactly happens with those depends on the GUI you use and any re-directs. if you run R in a shell without any re-directs then you will see both in the console:

```
$ R --silent
> library(rJava)
> .jinit(".")
> .jnew("Test")$launch()
Error:/private/tmp
Output:/private/tmp
java.util.InputMismatchException: fejfoejfwef
	at Test.launch(Test.java:10)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RJavaTools.invokeMethod(RJavaTools.java:399)
[1] "Hello this is eGPS for R!"
```

**Comment by yudalang3** [comment]
I think I already got it, But must people use R in the Rstudio. So we can not get the error or the std.
